//
// BIM IFC export alternate UI library: this library works with Autodesk(R) Revit(R) to provide an alternate user interface for the export of IFC files from Revit.
// Copyright (C) 2012  Autodesk, Inc.
// 
// This library is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public
// License as published by the Free Software Foundation; either
// version 2.1 of the License, or (at your option) any later version.
//
// This library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public
// License along with this library; if not, write to the Free Software
// Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
//

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIM.IFC.Export.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BIM.IFC.Export.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include base quantities.
        /// </summary>
        internal static string ExportBaseQuantities {
            get {
                return ResourceManager.GetString("ExportBaseQuantities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export parts as building elements.
        /// </summary>
        internal static string ExportPartsAsBuildingElements {
            get {
                return ResourceManager.GetString("ExportPartsAsBuildingElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export plan view elements.
        /// </summary>
        internal static string ExportPlanViewElements {
            get {
                return ResourceManager.GetString("ExportPlanViewElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Revit property sets.
        /// </summary>
        internal static string ExportRevitPropertySets {
            get {
                return ResourceManager.GetString("ExportRevitPropertySets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File type.
        /// </summary>
        internal static string FileType {
            get {
                return ResourceManager.GetString("FileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File version.
        /// </summary>
        internal static string FileVersion {
            get {
                return ResourceManager.GetString("FileVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2x3 CV2.0.
        /// </summary>
        internal static string IFCMVD2x3CV2 {
            get {
                return ResourceManager.GetString("IFCMVD2x3CV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2x2 BCA.
        /// </summary>
        internal static string IFCMVDBCA {
            get {
                return ResourceManager.GetString("IFCMVDBCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2x3 GSA.
        /// </summary>
        internal static string IFCMVDGSA {
            get {
                return ResourceManager.GetString("IFCMVDGSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2x2.
        /// </summary>
        internal static string IFCVersion2x2 {
            get {
                return ResourceManager.GetString("IFCVersion2x2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2x3.
        /// </summary>
        internal static string IFCVersion2x3 {
            get {
                return ResourceManager.GetString("IFCVersion2x3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized IFCVersion.
        /// </summary>
        internal static string IFCVersionUnrecognized {
            get {
                return ResourceManager.GetString("IFCVersionUnrecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include space boundaries.
        /// </summary>
        internal static string IncludeSpaceBoundaries {
            get {
                return ResourceManager.GetString("IncludeSpaceBoundaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;In-Session Setup&gt;.
        /// </summary>
        internal static string InSessionConfiguration {
            get {
                return ResourceManager.GetString("InSessionConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space boundaries.
        /// </summary>
        internal static string SpaceBoundaries {
            get {
                return ResourceManager.GetString("SpaceBoundaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1st Level.
        /// </summary>
        internal static string SpaceBoundaries1stLevel {
            get {
                return ResourceManager.GetString("SpaceBoundaries1stLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2nd Level.
        /// </summary>
        internal static string SpaceBoundaries2ndLevel {
            get {
                return ResourceManager.GetString("SpaceBoundaries2ndLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string SpaceBoundariesNone {
            get {
                return ResourceManager.GetString("SpaceBoundariesNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized space boundary level.
        /// </summary>
        internal static string SpaceBoundariesUnrecognized {
            get {
                return ResourceManager.GetString("SpaceBoundariesUnrecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split walls and columns.
        /// </summary>
        internal static string SplitWallsAndColumns {
            get {
                return ResourceManager.GetString("SplitWallsAndColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use 2D room boundaries for room volume.
        /// </summary>
        internal static string Use2DRoomBoundariesForRoomVolume {
            get {
                return ResourceManager.GetString("Use2DRoomBoundariesForRoomVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use family and type name for references.
        /// </summary>
        internal static string UseFamilyAndTypeNameForReferences {
            get {
                return ResourceManager.GetString("UseFamilyAndTypeNameForReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible elements of current view.
        /// </summary>
        internal static string VisibleElementsOfCurrentView {
            get {
                return ResourceManager.GetString("VisibleElementsOfCurrentView", resourceCulture);
            }
        }
    }
}
